apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /var/tmp
  containers:
  - name: hostpath-pod
    image: 'k8s.gcr.io/busybox'
    command: ["/bin/sh", "-c", "echo Hello Team, This is Sample File for HostVolume - $(date) >> /output/output.txt"]
    volumeMounts:
    - name: hostpath-vol
      mountPath: /output

make sure path "/var/tmp" is present 
kubectl apply -f hostpath-volume-mount.yml
kubectl get pod <pod_name> --watch
kubectl exec -it <pod_name> -- /bin/bash

apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-pod
    image: redis
    volumeMounts:
    - name: hostpath-vol
      mountPath: /data/redis
  - name: hostpath-vol
    hostPath:
      path: /var/tmp
