apiVersion: v1
kind: Pod
metadata:
  name: svc-test-dns
  namespace: service-namespace
spec:
  containers:
    - name: busybox-svc
      image: radial/busyboxplus:curl
      command:
        - sleep
        - '3600'

kubectl create namespace service-namespace
kubectl apply -f dns-service-pod.yml

kubectl exec -n service-namespace svc-test-dns -- curl nginx-service.default.svc.cluster.local:8080

service-name.namespace-name.svc.cluster-domain.example