apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: voting
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: vikas24775/postgres
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
